AllCops:
  Exclude:
    - db/**/**
    - api_test.rb
    - spec/**/**
    - config/**/**
    - Gemfile
Metrics/LineLength:
  Max: 150
Metrics/BlockLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 7